### ISSUE TITLE
Support HTML5

### ISSUE THREAD

**Issue by rajveerappan** [nahsra/antisamy#10]
AntiSamy uses a deprecated [HTMLSerializer](https://xerces.apache.org/xerces2-j/javadocs/other/org/apache/xml/serialize/HTMLSerializer.html) which does not understand newer HTML5 tags like [`<figure>`](https://stackoverflow.com/questions/32442493/why-does-owasp-antisamy-strip-out-the-figure-tag). While this is a minor issue, it also does not understand newer HTML5 entities like `&colon;` or `&lpar;`. This leads to a security vulnerability where the following text does not get cleaned:
```
<a href="javascript&colon;alert&lpar;1&rpar;">X</a>
```

**Comment by nahsra** [comment]
Confirmed, unfortunately! Will make a fix shortly.

**Comment by nahsra** [comment]
Any thoughts on any other attack vectors besides hiding a colon in a JavaScript URL? Although I'd love something more solid, it seems like the only choice is to effectively blacklist the substring:

&colon

... because all of its containing characters are required for accepting a URL.

**Comment by rajveerappan** [comment]
From the HTMLSanitizer docs:

> This class was deprecated in Xerces 2.6.2. It is recommended that new applications use JAXP's Transformation API for XML (TrAX) for serializing HTML. See the Xerces documentation for more information.

The ideal fix would be to switch to TrAX unless there are major roadblocks to doing so since that would not just fix this issue but also add support for HTML5. Blacklisting `&colon` might be an ok stopgap measure in the meantime.

**Comment by nahsra** [comment]
This is merged into 1.5.7 branch.

**Comment by nahsra** [comment]
This was given CVE-2017-14735.

**Comment by oliviernt** [comment]
Shouldn't this issue be fixed in 1.5.7? https://nvd.nist.gov/vuln/detail/CVE-2017-14735 has it listed for 1.5.7 and previous.

**Comment by tourea** [comment]
Given the confusion in the CVE report, should we consider this issue fixed in 1.5.7?

**Comment by davewichers** [comment]
Yes. And https://nvd.nist.gov/vuln/detail/CVE-2017-14735 has been updated to say OWASP AntiSamy before 1.5.7 allows XSS via HTML5 entities, as demonstrated by use of `&colon;` to construct a javascript: URL.

**Comment by kwwall** [comment]
Dang. What's your secret to getting NIST (or MITRE?) to respond so quickly?
It took them 6+ months to update CVE-2013-5679 as fixed in 2.1.0 and IMO,
it's still not clear the way they worded it. You really need to look at the
CPE to be sure.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by davewichers** [comment]
It's MITRE. The official CVE is here: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-14735. And NIST just hosts a copy. If you want a CVE fixed, go to this page: https://cveform.mitre.org/ and submit your change request along with supporting info. No clue how fast they usually are, but I did notice the CVE for this issue was fixed one day after the comment above saying the CVE was wrong, which I agree is blazing fast.

**Comment by kwwall** [comment]
Thanks. Good to know. I think I ended up emailing someone at NIST that I
found on one of the there pages and after significant hoop-jumping, found
someone who said that they would update it. And some 5 months later I
noticed it was updated. Never notified me or anything. Maybe things have
improved since then.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by mehtaharsh16** [comment]
According to me you are using lower version of the configuration for this project. May be by upgrading it's configuration and then using proper "WhitelistTagSerializer" or "tag" and many more will fix this bug. We can makenew WhitelistTagSerializer()object and then we can initialize inside one variable will fix this bug

ant = new WhitelistTagSerializer() we can use this.

Hope this will work.

**Comment by davewichers** [comment]
@mehtaharsh16 - Why are you commenting on an issue that was closed over 4 years ago?

**Comment by yanhui030503** [comment]
An unstoppable XSS vulnerability : )

**Comment by sahajkathiriya** [comment]
The vulnerability was reported and tracked as a public issue on GitHub. The issue's timeline provides a clear audit trail, showing the project owner confirming the bug, discussing potential fixes with the reporter, and linking to the fixing commit. The issue is formally marked as "Closed," indicating that the vulnerability has been successfully patched and resolved in subsequent releases.
