### ISSUE TITLE
Commit details for CVE-2022-28366?

### ISSUE THREAD

**Issue by codehelp** [nahsra/antisamy#174]
CVE-2022-28366 links to the release notes for 1.6.6 which include:
> CVEs for these have not been created yet, so we are not providing any details on the issues at this time.

Can the relevant details now be provided here, please?

**Comment by davewichers** [comment]
I updated the release notes for the v1.6.6, v.1.6.7, and v1.6.8 release tags. And also updated the SECURITY.md file with all this info. Is that sufficient?

**Comment by codehelp** [comment]
I'm specifically following up on https://security-tracker.debian.org/tracker/CVE-2022-28366
There is a need to identify the commit(s) which fix this CVE so that the versions in stable releases can be patched. A new upstream release is not suitable.
e.g. if there was one or more pull requests associated with the fix for this CVE, that would be sufficient.

**Comment by davewichers** [comment]
@codehelp - Did you read the updated release notes? https://github.com/nahsra/antisamy/releases/tag/v1.6.6 specifically states how this CVE was fixed. Note that this required an upgrade to a new library at different coordinates, so if you are maintaining your own fork, you'll have to do the same (which simply required changing the imports). If you are maintaining your own fork, then there are a number of other CVEs you'll need to address too.

I'm also not clear what you mean by: "so that the versions in stable releases can be patched" and "A new upstream release is not suitable." Why is not upgrading suitable?

**Comment by davewichers** [comment]
Closing as I haven't heard back in two months.
