### ISSUE TITLE
Is there a way to not encode certain HTML Entities?

### ISSUE THREAD

**Issue by enterlne** [nahsra/antisamy#362]
I need to sanitize user-entered URLs, which could include querystring parameters. Certain querystring parameters are being returned as HTML entities.
 
For example, "& p a r a" (minus the spaces) in the following URL value is returned as the pilcrow character (¶), and "& s e c t" is returned as the section character (§). The URL then becomes unusable.

https://www.google.com/search?q=aaaaaaaaa¶m=bbb§=ccc

How do I tell antisamy to not encode these characters, or to only encode them when they include the semicolon?

**Comment by enterlne** [comment]
We use AntiSamy to sanitize all user input data, after it is retrieved from the database. We do not use it only for URL data, but that is where this issue is seen, due to some URLs having specific querystring parameters.

Here is our scenario:
User opens a work order record and wants to attach a URL that points to some web page that is needed for the workorder
We provide a feature where they can enter any URL and save it to the work order
User enters "[https://www.google.com/search?q=aaaaaaaaa&param=bbb&sect=ccc]" in the URL field and then saves the record
The URL is saved in the database correctly (with "param" and "sect" as query parameter keys)
Another user then opens the work order record
At this point, the URL value is retrieved from the DB, goes through sanitize, and sanitize returns & p a r a as pilcrow (¶) and "& s e c t" as the section character (§). Because of this, when the user clicks on the link the URL does not open.

I have had success replacing the specific ¶ character with "&para" after sanitize, however that would need to be done for every possible HTML entity that is decoded by sanitize.

I have also tried encoding all ampersands (&amp;) prior to sanitize, however then the sanitization fails to remove malicious script tags.

We could use a different policy file for URL sanitization only, but I'm not sure if there is a way to change this behavior via policy file.

**Comment by kwwall** [comment]
@enterlne -  This is not to say that AntiSamy can't do this properly (I will let @spassarop address that), but in my personal opinion, you should be using output encoding here rather than sanitization. Thus I think you are using the wrong approach.

Unless you are actually trying to accept additional _markup_ rather than just a URL or some query parameters here (even if that markup is _just_ an \<A> tag), then HTML sanitization is likely the _wrong_ approach. Instead, you ought to be doing contextual output encoding. Since the context is a URL, you need to do URL encoding.

There are lots of ways to do this. You could use
-  OWASP ESAPI's [org.owasp.esapi.Encoder.encodeForURL](https://www.javadoc.io/static/org.owasp.esapi/esapi/2.5.2.0/org/owasp/esapi/Encoder.html#encodeForURL-java.lang.String-)
- OWASP Java Encoder Project's [org.owasp.encoder.Encode.encodeForUriComponent](https://javadoc.io/static/org.owasp.encoder/encoder/1.2.3/org/owasp/encoder/Encode.html#forUriComponent-java.lang.String-)
- [java.net.URLEncoder.encode](https://docs.oracle.com/javase/8/docs/api/java/net/URLEncoder.html#encode-java.lang.String-)
- Or, if you are doing this in a JSP, you could also use JSTL's Core Tags, c:url and c:param combination. (You _must_ use c:param for the query parameter portion for it to work properly to prevent XSS.)


Note that if you feed it the entire URL though to be encoded, the entire URL will be encoded, thus something like `https://example.com/search?q=abcparam&xyzsect=123` would be encoded as `https%3A%2F%2Fexample.com%2Fsearch%3Fq%3Dabcparam%26xyzsect%3D123`, which may or may not be exactly what you want. (If you don't want the protocol scheme and slashes encoded, only pass these functions the query string.)

Hope that helps.

**Comment by enterlne** [comment]
Hi @kwwall , 
Yes, that helps! URL encoding seems to do the job for x-site-scripts, and leave the HTML entities intact. I believe my issue is resolved. Thank you for you help!

**Comment by kwwall** [comment]
@enterlne - Great. Glad to here it. If that answer is sufficient, then please close the GitHub issue. Thanks.
