### ISSUE TITLE
antisamy ignoring anything rule?

### ISSUE THREAD

**Issue by clqian** [nahsra/antisamy#66]
i have a rule for an attribute in a tag that is like this:
`<tag name="tag1" action="validate" >
            <attribute name="attribute1">
                <regexp-list>
                    <regexp name="anything" />
                </regexp-list>
            </attribute>
            <attribute name="attribute2" />
        </tag>`
        
when i use the SAX parser, attribute1 is dropped because it has an LSEP character in it. it also may be dropping the filename for other characters. either way, shouldn't attribute1 not be dropped since the regexp has been assigned as `anything`?

the specific error message i'm getting is "The tag1 tag contained an attribute that we could not process. The attribute1 attribute had a value of "Gartner &#45; Executive Guide to Total Experience &#46;pdf". This value could not be accepted for security reasons. We have chosen to remove this attribute from the tag and leave everything else in place so that we could process the input."

**Comment by davewichers** [comment]
@spassarop - Can you answer this?

**Comment by spassarop** [comment]
Hi @clqian, DOM or SAX, any of them have the same issue with an LSEP character because the compiled Pattern for the regexp does not have the `Pattern.DOTALL` flag. Then, although you may want to match any character, it does not consider line separators.

If every compiled regexp has that flag on Policy parsing, it works. @davewichers do you think that would be ok? Change should be on 5 occurrences only in Policy class.

**Comment by davewichers** [comment]
I'm not qualified to comment on that. @nahsra - Arshan? What do you think?

**Comment by jdr023** [comment]
any updates on this?

**Comment by nahsra** [comment]
I agree with @clqian -- I think the character set being called literally "anything" should suggest that LSEP be allowed characters. We can't say for certain about how allowing LSEP would affect markup parsing in the browsers because they're essentially black boxes with unpredictable behavior at times, but I am comfortable with the change overall.

**Comment by spassarop** [comment]
Something I can add is that the LSEP char may not be included in the output. At least I tested it as a unicode char and I could not make it appear after the sacan :(

That change can be done tomorrow I think. It's really simple.

**Comment by davewichers** [comment]
Hey @clqia, @spassarop implemented a change to address this issue and I just merged it into the 1.6.0 branch. Can you review the change and test. And let us know if you think this fixes this issue properly? Can if you could do that tomorrow that would be great, as we are trying to get the 1.6.0 release out in the next few days. Thx

**Comment by clqian** [comment]
hi @davewichers @spassarop yes the changes work for me. thank you so much!

**Comment by davewichers** [comment]
OK. This issue will then be fixed in the 1.6.0 release, which should be coming out soon.

**Comment by davewichers** [comment]
This was addressed in commit 3f446c5691e2111c15121a176d9b0994ded3ea42 and AntiSamy v1.6.0 was released today with this included.
